name: anslin
description: "anslin"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  sqflite: ^2.4.2
  shared_preferences: ^2.2.3
  badges: ^3.1.2 
  intl: ^0.18.1
  path: ^1.8.3
  geolocator: ^12.0.0
  latlong2: ^0.9.1
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/img/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/app_icon.png"
  adaptive_icon_background: "#73e8a8" 
  adaptive_icon_foreground: "assets/img/app_icon.png"

flutter_native_splash:

  color: '#add8e6'

  image: 'assets/img/splash.png'

  color_dark: '#ffffff'

  image_dark: 'assets/img/splash.png'

  fullscreen: true

  android_12:

    icon_background_color: '#ffffff'

    image: 'assets/img/splash.png'

    icon_background_color_dark: '#262626'

    image_dark: 'assets/img/splash.png'